### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ghost** [w-gao/py-mcpe-stats#3]
```
nathfreder@Nathaniels-MacBook-Pro py-mcpe-stats % python main.py play.nethergames.org 19132
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    server_data = q.query()
  File "/Users/nathfreder/Coding/py-mcpe-stats/py_mcpe_stats/query.py", line 78, in query
    server_data.MOTD = info[7]
IndexError: list index out of range
```

**Comment by w-gao** [comment]
Hey, thanks for the feedback!

```python
py_mcpe_stats/query.py#L70

                if len(info) >= 6:
                    server_data.GAME_ID = info[0]
                    server_data.SERVER_NAME = info[1]
                    server_data.GAME_PROTOCOL = int(info[2])
                    server_data.GAME_VERSION = info[3]
                    server_data.NUM_PLAYERS = int(info[4])
                    server_data.MAX_PLAYERS = int(info[5])

                if len(info) >= 7:
                    server_data.HASH_CODE = info[6]

                if len(info) >= 9:
                    server_data.MOTD = info[7]
                    server_data.GAMEMODE = info[8]
```
(https://gist.github.com/w-gao/a2df002c5bad0e51c3fc1906ac41f0b7)

This *should* work for most servers, but there definitely should be some kind of error handling when parsing the data sent from the server. 


Do you mind creating a PR or do you want me to push a fix? :)

**Comment by w-gao** [comment]
This should be fixed. Please reopen if this still happens.
